<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Writer
    |--------------------------------------------------------------------------
    |
    | This option controls the default writer that will be used to write
    | the document. You can use any writer that is supported by PhpWord.
    |
    | Supported: "Word2007", "ODText", "RTF", "HTML", "PDF"
    |
    */
    'default_writer' => 'Word2007',

    /*
    |--------------------------------------------------------------------------
    | Default Font
    |--------------------------------------------------------------------------
    |
    | This option controls the default font settings for the documents.
    |
    */
    'default_font' => [
        'name' => 'Times New Roman',
        'size' => 12,
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Paper Settings
    |--------------------------------------------------------------------------
    |
    | This option controls the default paper settings for the documents.
    |
    */
    'default_paper' => [
        'size' => 'A4',
        'orientation' => 'portrait',
        'margins' => [
            'top' => \PhpOffice\PhpWord\Shared\Converter::cmToTwip(2.5),
            'bottom' => \PhpOffice\PhpWord\Shared\Converter::cmToTwip(2.5),
            'left' => \PhpOffice\PhpWord\Shared\Converter::cmToTwip(3),
            'right' => \PhpOffice\PhpWord\Shared\Converter::cmToTwip(3),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Document Settings
    |--------------------------------------------------------------------------
    |
    | Default settings for document properties.
    |
    */
    'document_properties' => [
        'creator' => 'SPPD-OI System',
        'company' => 'Pemda Ogan Ilir',
        'title' => 'SPPD Document',
        'description' => 'Document generated by SPPD-OI System',
        'category' => 'Government Document',
        'last_modified_by' => 'SPPD-OI System',
        'created' => null, // Will be set to current timestamp
        'modified' => null, // Will be set to current timestamp
        'subject' => 'Surat Perintah Perjalanan Dinas',
        'keywords' => 'SPPD, Perjalanan Dinas, Government',
    ],

    /*
    |--------------------------------------------------------------------------
    | Template Settings
    |--------------------------------------------------------------------------
    |
    | Settings for document templates.
    |
    */
    'templates' => [
        'path' => storage_path('app/templates/'),
        'output_path' => storage_path('app/documents/'),

        // Template files
        'sppd' => storage_path('app/templates/template_sppd.docx'),
        'surat_perintah' => storage_path('app/templates/template_surat_perintah.docx'),
        'laporan_perjalanan' => storage_path('app/templates/template_laporan_perjalanan.docx'),
        'kuitansi' => storage_path('app/templates/template_kuitansi.docx'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Style Settings
    |--------------------------------------------------------------------------
    |
    | Common style configurations for documents.
    |
    */
    'styles' => [
        'heading1' => [
            'name' => 'Times New Roman',
            'size' => 14,
            'bold' => true,
            'color' => '000000',
            'spaceAfter' => 240,
            'alignment' => 'center',
        ],
        'heading2' => [
            'name' => 'Times New Roman',
            'size' => 12,
            'bold' => true,
            'color' => '000000',
            'spaceAfter' => 120,
        ],
        'normal' => [
            'name' => 'Times New Roman',
            'size' => 12,
            'color' => '000000',
            'spaceAfter' => 120,
        ],
        'table_header' => [
            'name' => 'Times New Roman',
            'size' => 11,
            'bold' => true,
            'color' => '000000',
        ],
        'table_content' => [
            'name' => 'Times New Roman',
            'size' => 11,
            'color' => '000000',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Table Settings
    |--------------------------------------------------------------------------
    |
    | Default table styling configurations.
    |
    */
    'table_styles' => [
        'default' => [
            'borderSize' => 6,
            'borderColor' => '000000',
            'cellMargin' => 80,
            'alignment' => 'center',
            'width' => 100,
            'unit' => 'pct', // percent
        ],
        'no_border' => [
            'borderSize' => 0,
            'cellMargin' => 80,
            'alignment' => 'left',
            'width' => 100,
            'unit' => 'pct',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Number Format Settings
    |--------------------------------------------------------------------------
    |
    | Settings for number and currency formatting.
    |
    */
    'number_format' => [
        'currency' => [
            'symbol' => 'Rp ',
            'thousands_separator' => '.',
            'decimal_separator' => ',',
            'decimals' => 0,
        ],
        'date_format' => 'd F Y',
        'date_format_short' => 'd/m/Y',
    ],

    /*
    |--------------------------------------------------------------------------
    | Security Settings
    |--------------------------------------------------------------------------
    |
    | Settings for document security and protection.
    |
    */
    'security' => [
        'enable_protection' => false,
        'password' => null,
        'editing_type' => 'readOnly', // readOnly, forms, comments, trackedChanges
    ],

    /*
    |--------------------------------------------------------------------------
    | Watermark Settings
    |--------------------------------------------------------------------------
    |
    | Settings for document watermarks.
    |
    */
    'watermark' => [
        'enabled' => false,
        'text' => 'RAHASIA',
        'font' => [
            'name' => 'Times New Roman',
            'size' => 72,
            'color' => 'CCCCCC',
        ],
        'angle' => -45,
    ],
];
